(deftheme nova-theme
  "Created 2017-10-16.")

(custom-theme-set-faces
 'nova-theme
 '(cursor ((t (:background "#74AFB8"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#268bd2"))))
 '(highlight ((t (:background "#556874" :inverse-video nil))))
 '(region ((t (:inverse-video t :foreground "#586e75"))))
 '(shadow ((t (:foreground "#93a1a1"))))
 '(secondary-selection ((t (:background "#eee8d5"))))
 '(trailing-whitespace ((t (:underline nil :background "#dc322f"))))
 '(font-lock-builtin-face ((t (:foreground "#d18EC2"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#6a7d89" :slant italic))))
 '(font-lock-comment-face ((t (:foreground "#6a7d89" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#e18b8a"))))
 '(font-lock-doc-face ((t (:foreground "#899BA6"))))
 '(font-lock-function-name-face ((t (:foreground "#81aee7"))))
 '(font-lock-keyword-face ((t (:foreground "#a7cf90"))))
 '(font-lock-negation-char-face ((t (:foreground "#268bd2"))))
 '(font-lock-preprocessor-face ((t (:foreground "#f3c38b"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#6c71c4"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#d33682"))))
 '(font-lock-string-face ((t (:foreground "#7FC1CA"))))
 '(font-lock-type-face ((t (:foreground "#dadb8f"))))
 '(font-lock-variable-name-face ((t (:foreground "#83AFE5"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#dc322f"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line)))))
 '(link-visited ((t (:foreground "magenta4" :inherit (link)))))
 '(fringe ((t (:background "#3c4c55" :foreground "gray"))))
 '(header-line ((t (:foreground "#d33682" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:background "#3c4c55" :box (:line-width 1 :color "#899BA6") :weight normal))))
 '(mode-line-buffer-id ((t (:foreground "#F2C38F"))))
 '(mode-line-emphasis ((t (:foreground "#586e75"))))
 '(mode-line-highlight ((t (:weight bold :box nil :foreground "#d33682"))))
 '(mode-line-inactive ((t (:weight normal :box (:line-width 1 :color "#657b83" :style nil) :foreground "#93a1a1" :background "#eee8d5" :inherit (mode-line)))))
 '(isearch ((t (:inverse-video t :foreground "#b58900" :background "#fdf6e3"))))
 '(isearch-fail ((t (:inverse-video t :background "#fdf6e3" :inherit (font-lock-warning-face)))))
 '(lazy-highlight ((t (:inverse-video t :foreground "#2aa198" :background "#fdf6e3"))))
 '(match ((t (:inverse-video t :foreground "#268bd2" :background "#fdf6e3"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(default ((t (:inherit nil :stipple nil :background "#3C4C56" :foreground "#c4d4dd" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "monotype" :family "Noto Mono")))))

(provide-theme 'nova-theme)
